default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: basicruby
  username: postgres
  password: postgres
  host: localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: postgres
  username: basicruby
  password: basicruby
  host: localhost
  pool: 5
  timeout: 5000
